# Generated by Django 3.0.7 on 2020-12-19 07:56

from django.db import migrations, models
from covid_api.core.models import MyCreateView


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        MyCreateView(
            name='CasesSummaryView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_diagnostico', models.DateField(null=True)),
                ('carga_provincia_nombre', models.CharField(max_length=20)),
                ('casos', models.IntegerField(default=0)),
                ('muertes', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CovidCase',
            fields=[
                ('id_evento_caso', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=1, null=True)),
                ('edad', models.IntegerField(default=0, null=True)),
                ('edad_años_meses', models.CharField(max_length=5, null=True)),
                ('residencia_pais_nombre', models.CharField(max_length=20, null=True)),
                ('residencia_provincia_nombre', models.CharField(max_length=40, null=True)),
                ('residencia_departamento_nombre', models.CharField(max_length=80, null=True)),
                ('carga_provincia_nombre', models.CharField(max_length=20)),
                ('fecha_inicio_sintomas', models.DateField(null=True)),
                ('fecha_apertura', models.DateField(null=True)),
                ('sepi_apertura', models.IntegerField(default=0, null=True)),
                ('fecha_internacion', models.DateField(null=True)),
                ('cuidado_intensivo', models.CharField(max_length=2, null=True)),
                ('fecha_cui_intensivo', models.DateField(null=True)),
                ('fallecido', models.CharField(max_length=2, null=True)),
                ('fecha_fallecimiento', models.DateField(null=True)),
                ('asistencia_respiratoria_mecanica', models.CharField(max_length=2, null=True)),
                ('carga_provincia_id', models.IntegerField(default=0, null=True)),
                ('origen_financiamiento', models.CharField(max_length=20, null=True)),
                ('clasificacion', models.CharField(max_length=80, null=True)),
                ('clasificacion_resumen', models.CharField(max_length=12, null=True)),
                ('residencia_provincia_id', models.IntegerField(default=0, null=True)),
                ('fecha_diagnostico', models.DateField(null=True)),
                ('residencia_departamento_id', models.IntegerField(default=0, null=True)),
                ('ultima_actualizacion', models.DateField()),
            ],
        ),
    ]
