# Generated by Django 3.0.7 on 2020-12-16 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='casessummaryview',
            unique_together=set(),
        ),
    ]
