# Generated by Django 3.0.7 on 2020-12-19 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='covidcase',
            index_together={('carga_provincia_nombre', 'clasificacion_resumen')},
        ),
    ]
