# Generated by Django 3.0.7 on 2020-12-20 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201220_2304'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='covidcase',
            index_together={('carga_provincia_nombre', 'clasificacion_resumen', 'fecha_diagnostico', 'fallecido', 'cuidado_intensivo', 'asistencia_respiratoria_mecanica')},
        ),
    ]
