name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.2.6 # This is the action
        with:
          heroku_api_key: cbb8737e-2277-4061-8680-41519bb8e5b5
          heroku_app_name: "covid-itba-api" #Must be unique in Heroku
          heroku_email: "jpalacci@itba.edu.ar"